import type { ActionFunctionArgs } from "react-router";

import { authenticate } from "../shopify.server";

export async function action({ request }: ActionFunctionArgs) {
  try {
    const { admin } = await authenticate.admin(request);

    const body = await request.json();

    const productId = body.productId;

    if (!productId) {
      return Response.json(
        {
          success: false,
          error: "Product ID is required.",
        },
        {
          status: 400,
        },
      );
    }

    const response = await admin.graphql(
      `#graphql
        query AnalyzeProduct($id: ID!) {
          product(id: $id) {
            id
            title
            handle
            description
            productType
            vendor
            status
            tags

            seo {
              title
              description
            }

            featuredImage {
              url
              altText
            }
          }
        }
      `,
      {
        variables: {
          id: productId,
        },
      },
    );

    const responseJson = await response.json();

    if (responseJson.errors?.length) {
      console.error(
        "[AI Product Optimizer] GraphQL error:",
        responseJson.errors,
      );

      return Response.json(
        {
          success: false,
          error: "Unable to load product from Shopify.",
        },
        {
          status: 500,
        },
      );
    }

    const product = responseJson.data?.product;

    if (!product) {
      return Response.json(
        {
          success: false,
          error: "Product not found.",
        },
        {
          status: 404,
        },
      );
    }

    /*
     * ---------------------------------------------------------------
     * Temporary analysis
     * ---------------------------------------------------------------
     *
     * This is NOT the real AI yet.
     *
     * We are first proving that:
     *
     * Product page
     *      ↓
     * API
     *      ↓
     * Shopify
     *      ↓
     * Analysis
     *      ↓
     * Product page
     *
     * works correctly.
     */

    const description = product.description?.trim() ?? "";

    const title = product.title?.trim() ?? "";

    const seoTitle = product.seo?.title?.trim() ?? "";

    const seoDescription = product.seo?.description?.trim() ?? "";

    const tags = product.tags ?? [];

    const checks = {
      title: title.length > 0,
      description: description.length > 0,
      seoTitle: seoTitle.length > 0,
      seoDescription: seoDescription.length > 0,
      tags: tags.length > 0,
    };

    const passedChecks = Object.values(checks).filter(Boolean).length;

    const totalChecks = Object.values(checks).length;

    const score = Math.round((passedChecks / totalChecks) * 100);

    const status =
      score === 100 ? "optimized" : score >= 60 ? "partial" : "needs_work";

    /*
     * Temporary recommendations.
     *
     * These will later be generated by AI.
     */

    const analysis = {
      score,

      summary:
        score === 100
          ? "Your product content currently meets the basic optimization checks."
          : "Your product has several opportunities to improve SEO, discoverability and conversion.",

      title: {
        current: title,

        suggested: title || "Improve your product title with relevant keywords",

        reason: title
          ? "The current title is available. AI can later improve its keyword relevance, clarity and conversion potential."
          : "A clear product title helps shoppers and search engines understand the product.",
      },

      description: {
        current: description,

        suggested:
          description ||
          "Add a detailed product description explaining the product's key features, benefits and use cases.",

        reason: description
          ? "The product has description content. AI can improve its structure, clarity and search relevance."
          : "A detailed product description helps customers understand the product and provides useful search context.",
      },

      seo: {
        title: {
          current: product.seo?.title ?? null,

          suggested: seoTitle || `${title} | Shop Now`,

          reason: seoTitle
            ? "An SEO title already exists and can be refined further."
            : "Adding an SEO title gives search engines a clearer page title.",
        },

        description: {
          current: product.seo?.description ?? null,

          suggested:
            seoDescription ||
            `Discover ${title}. Learn more about this product, its features and benefits.`,

          reason: seoDescription
            ? "An SEO description already exists and can be improved for relevance and click-through rate."
            : "An SEO description can improve how the product appears in search results.",
        },
      },

      tags: {
        current: tags,

        suggested: tags.length > 0 ? tags : ["product", "shopify", "featured"],

        reason:
          tags.length > 0
            ? "Existing tags can later be analyzed and expanded using AI."
            : "Relevant product tags can improve organization and discoverability.",
      },

      recommendations: [
        {
          priority: title.length > 0 ? "medium" : "high",

          category: "Product title",

          recommendation:
            title.length > 0
              ? "Review the product title for keyword relevance and clarity."
              : "Add a descriptive product title containing the most important product keywords.",
        },

        {
          priority: description.length > 0 ? "medium" : "high",

          category: "Description",

          recommendation:
            description.length > 0
              ? "Improve the structure and readability of the product description."
              : "Add a detailed product description covering features, benefits and use cases.",
        },

        {
          priority:
            seoTitle.length > 0 && seoDescription.length > 0 ? "low" : "high",

          category: "SEO",

          recommendation:
            seoTitle.length > 0 && seoDescription.length > 0
              ? "Review SEO metadata for keyword relevance."
              : "Add missing SEO metadata to improve search visibility.",
        },
      ],
    };

    return Response.json({
      success: true,

      product: {
        id: product.id,
        title: product.title,
      },

      analysis,

      status,
    });
  } catch (error) {
    console.error("[AI Product Optimizer] Analysis failed:", error);

    return Response.json(
      {
        success: false,
        error: "Product analysis failed.",
      },
      {
        status: 500,
      },
    );
  }
}
